In [1]:
!which python

/home/asa/miniconda3/envs/TensorFlow-Development/bin/python


In [2]:
# Importing the packages
import tensorflow as tf
import numpy as np

2024-08-16 00:04:35.335124: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-16 00:04:35.344289: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-16 00:04:35.347028: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-16 00:04:35.847523: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
# Checking the tensorflow version
print(tf.__version__)
!python3 -c "import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'; import tensorflow as tf; print('Num GPUs Available: ', len(tf.config.list_physical_devices('GPU')))"

2.17.0
I0000 00:00:1723746882.348949   23186 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1723746882.368683   23186 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1723746882.370164   23186 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
Num GPUs Available:  1


In [59]:
# Constants
c1 = tf.constant(7)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [60]:
# Check the dim of a tensor
c1.ndim

0

In [61]:
# Creating the vector
v1 = tf.constant([1,2,3])
print(v1)
print(v1.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1


In [62]:
# Creating the matrix
m1 = tf.constant([[1,2],
                  [3,4]])
print(m1)
print(m1.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2


In [63]:
# Specifying the dtype for the tensor
print(c1.dtype)
c2=tf.constant(3, dtype=tf.int64)
print(c2.dtype)

<dtype: 'int32'>
<dtype: 'int64'>


In [64]:
m2 = tf.constant([[3.,2.],
                  [3.,42.]], dtype=tf.float64)
m2
# Does the tf stores the value of the tensors as a numpy array

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.,  2.],
       [ 3., 42.]])>

In [65]:
# Tensors with the higher dimension
t1 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[1,2]]])
t1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]], dtype=int32)>

In [3]:
# Creating tensors with variables
changable_tensor = tf.Variable([2,4])
unchangable_tensor = tf.constant([2,4])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>)

In [4]:
v1 = tf.Variable([[2,3],[3,2]])
v1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [3, 2]], dtype=int32)>

In [7]:
# Change the element of the changable tensor
changable_tensor[0] = 20
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [9]:
# The assignmenrt operator is not overloaded for the assignment operation in the tf.Variable method
# We need to use the .assign() method for it
changable_tensor[0].assign(20)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  4], dtype=int32)>

In [12]:
changable_tensor.assign([2,2])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [17]:
# Cannot assign an element out of the index
changable_tensor[2].assign(30)
changable_tensor

2024-08-08 17:23:38.103423: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at strided_slice_op.cc:117 : INVALID_ARGUMENT: slice index 2 of dimension 0 out of bounds.
2024-08-08 17:23:38.103446: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: slice index 2 of dimension 0 out of bounds.


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} slice index 2 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [67]:
# Creating Random tensors
generator = tf.random.Generator.from_seed(42)
generator      # set the seed for reproducibility

In [68]:
r1 = generator.normal(shape=(3,2))
r1     # outputs the values from normal distribution

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [77]:
r2 = generator.uniform(shape=[2,3], minval=2, maxval=10)
r2    # output values from a uniform distribution

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[7.4349947, 6.12593  , 4.978739 ],
       [6.9099865, 9.944253 , 9.1576605]], dtype=float32)>

In [81]:
# Checking the reproducibility of the generators
g1 = tf.random.Generator.from_seed(10)
g2 = tf.random.Generator.from_seed(10)
rand1 = g1.normal( shape=(3,3) )
rand2 = g2.normal( shape=(3,3) )

rand1, rand2, rand1==rand2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.29604468, -0.21134208,  0.01063002],
        [ 1.5165398 ,  0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307, -1.0130817 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.29604468, -0.21134208,  0.01063002],
        [ 1.5165398 ,  0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307, -1.0130817 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [83]:
# Shuffle the order of the elements in the tensor
not_shuffle = tf.range(1, 100)
not_shuffle

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)>

In [84]:
shuffle = tf.random.shuffle(not_shuffle)
shuffle

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([88, 82, 62, 49, 34, 25, 89, 66, 68, 87, 74, 55, 30, 43,  2, 67, 16,
       70, 50, 96, 57, 13, 81, 76, 40,  3, 84, 92, 32, 26, 61, 45, 37, 98,
       93, 52,  4, 47, 83, 71, 63,  7, 21, 77, 64, 31, 69, 65, 20, 42, 85,
       38, 94, 41, 35, 51, 18, 58, 56, 95, 59,  6, 33, 60, 80, 19, 23, 99,
       10, 44,  9, 15, 53, 22, 39, 90, 11, 27, 14,  5, 48, 79, 29,  8, 75,
       86, 91, 12, 36, 46,  1, 97, 17, 28, 78, 72, 54, 24, 73],
      dtype=int32)>

In [28]:
# In the 2-D tensor the order of each individual element changes
# But the order within the inner tensor remains the same
ten_ns = tf.constant([[1,2],[3,4],[5,6]])
ten_ns

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [29]:
ten_s = tf.random.shuffle(ten_ns)
ten_s

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [44]:
ten_s_seed_1 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_s_seed_2 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_s_seed_1, ten_s_seed_2

(<tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([12, 11, 14,  4,  8,  5,  1, 18, 16, 10,  2, 17,  3,  7,  9, 15, 13,
         6, 19], dtype=int32)>,
 <tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([18,  8,  6, 19, 12, 15, 17,  9, 11,  4, 13, 16, 14,  2,  3,  7,  1,
        10,  5], dtype=int32)>)

In [45]:
ten_s_seed_1 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_s_seed_2 = tf.random.shuffle(tf.range(1, 20,), seed=10)
# Reason why we get diff. values is that the second call uses a different operation seed.
ten_s_seed_1, ten_s_seed_2

(<tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([ 7,  5,  9,  4, 14, 10, 13, 19,  2, 12, 18,  1, 11,  8,  3, 15,  6,
        16, 17], dtype=int32)>,
 <tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([ 4, 11,  6,  5, 12, 10,  3,  1, 13,  8, 16, 15, 19,  7, 14,  2, 18,
         9, 17], dtype=int32)>)

In [46]:
tf.random.set_seed(10)
ten_gs_seed_1 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_gs_seed_2 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_gs_seed_1, ten_gs_seed_2

(<tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([13, 11,  8,  7,  6, 17, 16, 19,  1, 15, 14,  3, 10,  5,  9, 12, 18,
         4,  2], dtype=int32)>,
 <tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([14,  6,  2,  5,  3, 17, 16,  9,  1, 11, 13,  4, 18, 15, 10, 19,  7,
        12,  8], dtype=int32)>)

In [48]:
tf.random.set_seed(10)
ten_gs_seed_1 = tf.random.shuffle(tf.range(1, 20,), seed=10)
ten_gs_seed_2 = tf.random.shuffle(tf.range(1, 20,), seed=10)
# Reason why they individually generate the same sequence again when we re-run the code
# Is because the the uses the same explicitly set global seed
ten_gs_seed_1, ten_gs_seed_2

(<tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([13, 11,  8,  7,  6, 17, 16, 19,  1, 15, 14,  3, 10,  5,  9, 12, 18,
         4,  2], dtype=int32)>,
 <tf.Tensor: shape=(19,), dtype=int32, numpy=
 array([14,  6,  2,  5,  3, 17, 16,  9,  1, 11, 13,  4, 18, 15, 10, 19,  7,
        12,  8], dtype=int32)>)

In [62]:
# Interaction Between Global and Operation-Level Seeds

# 1. Neither Global Seed Nor Operation Seed Is Set:
tf.random.set_seed(None)
ngos = tf.random.shuffle(tf.range(1, 11))

# 2. Global Seed Set, But Operation Seed Not Set
tf.random.set_seed(10)
gsons = tf.random.shuffle(tf.range(1, 11))

# 3. Operation Seed Set, But Global Seed Not Set
tf.random.set_seed(None)
gnsos = tf.random.shuffle(tf.range(1, 11))

# 4. Both Global and Operation Seeds Are Set
tf.random.set_seed(10)
gsos = tf.random.shuffle(tf.range(1, 11))

ngos, gsons, gnsos, gsos

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 5,  4,  6,  7, 10,  3,  9,  8,  1,  2], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1, 10,  5,  7,  3,  6,  4,  2,  8,  9], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 2, 10,  8,  1,  6,  7,  9,  5,  4,  3], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1, 10,  5,  7,  3,  6,  4,  2,  8,  9], dtype=int32)>)

In [63]:
# Interaction Between Global and Operation-Level Seeds

# 1. Neither Global Seed Nor Operation Seed Is Set:
tf.random.set_seed(None)
ngos = tf.random.shuffle(tf.range(1, 11))

# 2. Global Seed Set, But Operation Seed Not Set
tf.random.set_seed(10)
gsons = tf.random.shuffle(tf.range(1, 11))

# 3. Operation Seed Set, But Global Seed Not Set
tf.random.set_seed(None)
gnsos = tf.random.shuffle(tf.range(1, 11))

# 4. Both Global and Operation Seeds Are Set
tf.random.set_seed(10)
gsos = tf.random.shuffle(tf.range(1, 11))

ngos, gsons, gnsos, gsos

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  9,  6,  2,  3,  5,  4, 10,  7,  8], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1, 10,  5,  7,  3,  6,  4,  2,  8,  9], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  3,  2,  7, 10,  8,  4,  5,  9,  6], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1, 10,  5,  7,  3,  6,  4,  2,  8,  9], dtype=int32)>)

In [10]:
# Convert the numpy array into tf tensor
na =  np.arange(1,11, dtype=np.int32)
# While re-shaping the numpy array the number of element in the numpy array should be
# equal to the number of elements in the tf tensors
# 1*2*5 = 10 == len(na) = 10
ta = tf.constant(na, shape=(1,2,5))
na, ta

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32),
 <tf.Tensor: shape=(1, 2, 5), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]], dtype=int32)>)

In [24]:
# Getting informations from the tensors
tensor = tf.constant(np.arange(1, 101), shape=(1,2,5,5,2))
# print("Sample tensor : ")
# print(tensor)

# To check the rank of the tensors
print(f"Dimensions (Rank) : {tensor.ndim}")

# To check shape of the tensors
print(f"Shape : {tensor.shape}")

# To check the size of the tensors
print(f"Size : {tf.size(tensor)}")
print(f"Size of inner array : {tf.size(tensor[0][0])}")

Dimensions (Rank) : 5
Shape : (1, 2, 5, 5, 2)
Size : 100
Size of inner array : 50


In [25]:
# Access a particular Axis / Dimensions
tensor[0,1], tensor[0][1], tensor[0,1]==tensor[0][1]

(<tf.Tensor: shape=(5, 5, 2), dtype=int64, numpy=
 array([[[ 51,  52],
         [ 53,  54],
         [ 55,  56],
         [ 57,  58],
         [ 59,  60]],
 
        [[ 61,  62],
         [ 63,  64],
         [ 65,  66],
         [ 67,  68],
         [ 69,  70]],
 
        [[ 71,  72],
         [ 73,  74],
         [ 75,  76],
         [ 77,  78],
         [ 79,  80]],
 
        [[ 81,  82],
         [ 83,  84],
         [ 85,  86],
         [ 87,  88],
         [ 89,  90]],
 
        [[ 91,  92],
         [ 93,  94],
         [ 95,  96],
         [ 97,  98],
         [ 99, 100]]])>,
 <tf.Tensor: shape=(5, 5, 2), dtype=int64, numpy=
 array([[[ 51,  52],
         [ 53,  54],
         [ 55,  56],
         [ 57,  58],
         [ 59,  60]],
 
        [[ 61,  62],
         [ 63,  64],
         [ 65,  66],
         [ 67,  68],
         [ 69,  70]],
 
        [[ 71,  72],
         [ 73,  74],
         [ 75,  76],
         [ 77,  78],
         [ 79,  80]],
 
        [[ 81,  82],
         [ 83,

In [28]:
print(f"Elements at the 0th axis : {tensor.shape[0]}")
print(f"Elements at the last axis : {tensor.shape[-1]}")

Elements at the 0th axis : 1
Elements at the last axis : 2


In [29]:
# Checking the returning class
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([1, 2, 5, 5, 2]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=100>)

In [31]:
# Converting the tf.tensors to numpy array
tensor.numpy()

array([[[[[  1,   2],
          [  3,   4],
          [  5,   6],
          [  7,   8],
          [  9,  10]],

         [[ 11,  12],
          [ 13,  14],
          [ 15,  16],
          [ 17,  18],
          [ 19,  20]],

         [[ 21,  22],
          [ 23,  24],
          [ 25,  26],
          [ 27,  28],
          [ 29,  30]],

         [[ 31,  32],
          [ 33,  34],
          [ 35,  36],
          [ 37,  38],
          [ 39,  40]],

         [[ 41,  42],
          [ 43,  44],
          [ 45,  46],
          [ 47,  48],
          [ 49,  50]]],


        [[[ 51,  52],
          [ 53,  54],
          [ 55,  56],
          [ 57,  58],
          [ 59,  60]],

         [[ 61,  62],
          [ 63,  64],
          [ 65,  66],
          [ 67,  68],
          [ 69,  70]],

         [[ 71,  72],
          [ 73,  74],
          [ 75,  76],
          [ 77,  78],
          [ 79,  80]],

         [[ 81,  82],
          [ 83,  84],
          [ 85,  86],
          [ 87,  88],
          [ 89

In [32]:
# Indexing of the tensors

# sample tensor
tensor

<tf.Tensor: shape=(1, 2, 5, 5, 2), dtype=int64, numpy=
array([[[[[  1,   2],
          [  3,   4],
          [  5,   6],
          [  7,   8],
          [  9,  10]],

         [[ 11,  12],
          [ 13,  14],
          [ 15,  16],
          [ 17,  18],
          [ 19,  20]],

         [[ 21,  22],
          [ 23,  24],
          [ 25,  26],
          [ 27,  28],
          [ 29,  30]],

         [[ 31,  32],
          [ 33,  34],
          [ 35,  36],
          [ 37,  38],
          [ 39,  40]],

         [[ 41,  42],
          [ 43,  44],
          [ 45,  46],
          [ 47,  48],
          [ 49,  50]]],


        [[[ 51,  52],
          [ 53,  54],
          [ 55,  56],
          [ 57,  58],
          [ 59,  60]],

         [[ 61,  62],
          [ 63,  64],
          [ 65,  66],
          [ 67,  68],
          [ 69,  70]],

         [[ 71,  72],
          [ 73,  74],
          [ 75,  76],
          [ 77,  78],
          [ 79,  80]],

         [[ 81,  82],
          [ 83,  84],
   

In [52]:
# Getting the 1st column
tensor[:,:,:,:,0]

<tf.Tensor: shape=(1, 2, 5, 5), dtype=int64, numpy=
array([[[[ 1,  3,  5,  7,  9],
         [11, 13, 15, 17, 19],
         [21, 23, 25, 27, 29],
         [31, 33, 35, 37, 39],
         [41, 43, 45, 47, 49]],

        [[51, 53, 55, 57, 59],
         [61, 63, 65, 67, 69],
         [71, 73, 75, 77, 79],
         [81, 83, 85, 87, 89],
         [91, 93, 95, 97, 99]]]])>

In [53]:
# Getting the 1st element in all the dimensions
tensor[:1,:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=int64, numpy=array([[[[[1]]]]])>

In [55]:
# Getting the 1st element from each dimenstionexcept from the final one
tensor[:1,:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 1, 2), dtype=int64, numpy=array([[[[[1, 2]]]]])>

In [65]:
# Getting the last item of all the tensor in the last dimension
tensor[:,:,:,:,-1]

<tf.Tensor: shape=(1, 2, 5, 5), dtype=int64, numpy=
array([[[[  2,   4,   6,   8,  10],
         [ 12,  14,  16,  18,  20],
         [ 22,  24,  26,  28,  30],
         [ 32,  34,  36,  38,  40],
         [ 42,  44,  46,  48,  50]],

        [[ 52,  54,  56,  58,  60],
         [ 62,  64,  66,  68,  70],
         [ 72,  74,  76,  78,  80],
         [ 82,  84,  86,  88,  90],
         [ 92,  94,  96,  98, 100]]]])>

In [60]:
# re-shaping a tensor
# while reshaping a tensor the size of the original and reshaped tensor should be equal
# ie., 1*10=10 == 2*5=10
ot = tf.constant(tf.range(1,11),shape=(1,10))
rt = tf.reshape(ot, shape=(2,5))

print(f"Original tensor shape : {ot.shape}")
print(f"Reshaped tensor shape : {rt.shape}")

Original tensor shape : (1, 10)
Reshaped tensor shape : (2, 5)


In [61]:
ot, rt

(<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=int32)>)

In [62]:
tf.constant(ot)

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

In [63]:
# Converting a constant tensor to variable tensor
tf.Variable(ot)

<tf.Variable 'Variable:0' shape=(1, 10) dtype=int32, numpy=array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)>

In [64]:
# Converting back a variable tensor to constant tensor
tf.constant(ot, shape=(5,2))

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]], dtype=int32)>

In [66]:
# Adding an extra dimensions in an existing tensor
tensor.shape

TensorShape([1, 2, 5, 5, 2])

In [76]:
# Adding a new dimension by using the Ellipsis(...)
aedt1 = tensor[..., tf.newaxis]
aedt1.shape, aedt1.ndim

(TensorShape([1, 2, 5, 5, 2, 1]), 6)

In [77]:
aedt1

<tf.Tensor: shape=(1, 2, 5, 5, 2, 1), dtype=int64, numpy=
array([[[[[[  1],
           [  2]],

          [[  3],
           [  4]],

          [[  5],
           [  6]],

          [[  7],
           [  8]],

          [[  9],
           [ 10]]],


         [[[ 11],
           [ 12]],

          [[ 13],
           [ 14]],

          [[ 15],
           [ 16]],

          [[ 17],
           [ 18]],

          [[ 19],
           [ 20]]],


         [[[ 21],
           [ 22]],

          [[ 23],
           [ 24]],

          [[ 25],
           [ 26]],

          [[ 27],
           [ 28]],

          [[ 29],
           [ 30]]],


         [[[ 31],
           [ 32]],

          [[ 33],
           [ 34]],

          [[ 35],
           [ 36]],

          [[ 37],
           [ 38]],

          [[ 39],
           [ 40]]],


         [[[ 41],
           [ 42]],

          [[ 43],
           [ 44]],

          [[ 45],
           [ 46]],

          [[ 47],
           [ 48]],

          [[ 49],
    

In [78]:
aedt2 = tensor[...,tf.newaxis,tf.newaxis]
aedt2.shape, aedt2.ndim

(TensorShape([1, 2, 5, 5, 2, 1, 1]), 7)

In [79]:
aedt2

<tf.Tensor: shape=(1, 2, 5, 5, 2, 1, 1), dtype=int64, numpy=
array([[[[[[[  1]],

           [[  2]]],


          [[[  3]],

           [[  4]]],


          [[[  5]],

           [[  6]]],


          [[[  7]],

           [[  8]]],


          [[[  9]],

           [[ 10]]]],



         [[[[ 11]],

           [[ 12]]],


          [[[ 13]],

           [[ 14]]],


          [[[ 15]],

           [[ 16]]],


          [[[ 17]],

           [[ 18]]],


          [[[ 19]],

           [[ 20]]]],



         [[[[ 21]],

           [[ 22]]],


          [[[ 23]],

           [[ 24]]],


          [[[ 25]],

           [[ 26]]],


          [[[ 27]],

           [[ 28]]],


          [[[ 29]],

           [[ 30]]]],



         [[[[ 31]],

           [[ 32]]],


          [[[ 33]],

           [[ 34]]],


          [[[ 35]],

           [[ 36]]],


          [[[ 37]],

           [[ 38]]],


          [[[ 39]],

           [[ 40]]]],



         [[[[ 41]],

           [[ 42]]],


       

In [80]:
# To explicitly specifying that the new axis should be added after the third dimension (index 2)
aedt3 = tensor[:,:,tf.newaxis]
aedt3.shape

TensorShape([1, 2, 1, 5, 5, 2])

In [81]:
aedt3

<tf.Tensor: shape=(1, 2, 1, 5, 5, 2), dtype=int64, numpy=
array([[[[[[  1,   2],
           [  3,   4],
           [  5,   6],
           [  7,   8],
           [  9,  10]],

          [[ 11,  12],
           [ 13,  14],
           [ 15,  16],
           [ 17,  18],
           [ 19,  20]],

          [[ 21,  22],
           [ 23,  24],
           [ 25,  26],
           [ 27,  28],
           [ 29,  30]],

          [[ 31,  32],
           [ 33,  34],
           [ 35,  36],
           [ 37,  38],
           [ 39,  40]],

          [[ 41,  42],
           [ 43,  44],
           [ 45,  46],
           [ 47,  48],
           [ 49,  50]]]],



        [[[[ 51,  52],
           [ 53,  54],
           [ 55,  56],
           [ 57,  58],
           [ 59,  60]],

          [[ 61,  62],
           [ 63,  64],
           [ 65,  66],
           [ 67,  68],
           [ 69,  70]],

          [[ 71,  72],
           [ 73,  74],
           [ 75,  76],
           [ 77,  78],
           [ 79,  80]],

  

In [83]:
# Adding a new dimension by using the tf.expand_dims() method
aedt4 = tf.expand_dims(tensor, axis=2)
aedt4.shape

TensorShape([1, 2, 1, 5, 5, 2])

In [84]:
aedt4

<tf.Tensor: shape=(1, 2, 1, 5, 5, 2), dtype=int64, numpy=
array([[[[[[  1,   2],
           [  3,   4],
           [  5,   6],
           [  7,   8],
           [  9,  10]],

          [[ 11,  12],
           [ 13,  14],
           [ 15,  16],
           [ 17,  18],
           [ 19,  20]],

          [[ 21,  22],
           [ 23,  24],
           [ 25,  26],
           [ 27,  28],
           [ 29,  30]],

          [[ 31,  32],
           [ 33,  34],
           [ 35,  36],
           [ 37,  38],
           [ 39,  40]],

          [[ 41,  42],
           [ 43,  44],
           [ 45,  46],
           [ 47,  48],
           [ 49,  50]]]],



        [[[[ 51,  52],
           [ 53,  54],
           [ 55,  56],
           [ 57,  58],
           [ 59,  60]],

          [[ 61,  62],
           [ 63,  64],
           [ 65,  66],
           [ 67,  68],
           [ 69,  70]],

          [[ 71,  72],
           [ 73,  74],
           [ 75,  76],
           [ 77,  78],
           [ 79,  80]],

  

In [87]:
# Checking the result obtained by the ellipsis method and expand_dims method are same
# for adding a new axis(dimension) at the 2nd index
aedt3 == aedt4

<tf.Tensor: shape=(1, 2, 1, 5, 5, 2), dtype=bool, numpy=
array([[[[[[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]],

          [[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]],

          [[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]],

          [[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]],

          [[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]]]],



        [[[[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True]],

          [[ True,  True],
           [ True,  True],
           [ True,  True],
           [ True,  True],
         

In [94]:
# Squeezing a tensor
mdft = tensor[..., tf.newaxis]
mdft.shape

TensorShape([1, 2, 5, 5, 2, 1])

In [96]:
szt1=tf.squeeze(mdft, axis=-1)
szt1.shape

TensorShape([1, 2, 5, 5, 2])

In [98]:
szt2=tf.squeeze(mdft, axis=0)
szt2.shape

TensorShape([2, 5, 5, 2, 1])

In [101]:
# If the axis is not specified it squeezes all the dimension with shape 1
szt3=tf.squeeze(mdft)
szt3.shape

TensorShape([2, 5, 5, 2])

In [13]:
# .eval() and .numpy() results the same
tf.range(3,432).numpy()

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 18