In [1]:
!which python

/home/asa/anaconda3/envs/TensorFlow-Development/bin/python


In [1]:
# Importing the packages
import tensorflow as tf

2024-08-08 16:53:03.572440: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [47]:
# Checking the tensorflow version
print(tf.__version__)

2.16.1


In [59]:
# Constants
c1 = tf.constant(7)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [60]:
# Check the dim of a tensor
c1.ndim

0

In [61]:
# Creating the vector
v1 = tf.constant([1,2,3])
print(v1)
print(v1.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1


In [62]:
# Creating the matrix
m1 = tf.constant([[1,2],
                  [3,4]])
print(m1)
print(m1.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2


In [63]:
# Specifying the dtype for the tensor
print(c1.dtype)
c2=tf.constant(3, dtype=tf.int64)
print(c2.dtype)

<dtype: 'int32'>
<dtype: 'int64'>


In [64]:
m2 = tf.constant([[3.,2.],
                  [3.,42.]], dtype=tf.float64)
m2
# Does the tf stores the value of the tensors as a numpy array

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.,  2.],
       [ 3., 42.]])>

In [65]:
# Tensors with the higher dimension
t1 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[1,2]]])
t1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]], dtype=int32)>

In [3]:
# Creating tensors with variables
changable_tensor = tf.Variable([2,4])
unchangable_tensor = tf.constant([2,4])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>)

In [4]:
v1 = tf.Variable([[2,3],[3,2]])
v1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [3, 2]], dtype=int32)>

In [7]:
# Change the element of the changable tensor
changable_tensor[0] = 20
changable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [9]:
# The assignmenrt operator is not overloaded for the assignment operation in the tf.Variable method
# We need to use the .assign() method for it
changable_tensor[0].assign(20)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  4], dtype=int32)>

In [12]:
changable_tensor.assign([2,2])
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

In [17]:
# Cannot assign an element out of the index
changable_tensor[2].assign(30)
changable_tensor

2024-08-08 17:23:38.103423: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at strided_slice_op.cc:117 : INVALID_ARGUMENT: slice index 2 of dimension 0 out of bounds.
2024-08-08 17:23:38.103446: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: slice index 2 of dimension 0 out of bounds.


InvalidArgumentError: {{function_node __wrapped__StridedSlice_device_/job:localhost/replica:0/task:0/device:GPU:0}} slice index 2 of dimension 0 out of bounds. [Op:StridedSlice] name: strided_slice/

In [67]:
# Creating Random tensors
generator = tf.random.Generator.from_seed(42)
generator      # set the seed for reproducibility

In [68]:
r1 = generator.normal(shape=(3,2))
r1     # outputs the values from normal distribution

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [77]:
r2 = generator.uniform(shape=[2,3], minval=2, maxval=10)
r2    # output values from a uniform distribution

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[7.4349947, 6.12593  , 4.978739 ],
       [6.9099865, 9.944253 , 9.1576605]], dtype=float32)>

In [81]:
# Checking the reproducibility of the generators
g1 = tf.random.Generator.from_seed(10)
g2 = tf.random.Generator.from_seed(10)
rand1 = g1.normal( shape=(3,3) )
rand2 = g2.normal( shape=(3,3) )

rand1, rand2, rand1==rand2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.29604468, -0.21134208,  0.01063002],
        [ 1.5165398 ,  0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307, -1.0130817 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-0.29604468, -0.21134208,  0.01063002],
        [ 1.5165398 ,  0.2730574 , -0.29925638],
        [-0.3652325 ,  0.61883307, -1.0130817 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]])>)

In [83]:
# Shuffle the order of the elements in the tensor
not_shuffle = tf.range(1, 100)
not_shuffle

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)>

In [84]:
shuffle = tf.random.shuffle(not_shuffle)
shuffle

<tf.Tensor: shape=(99,), dtype=int32, numpy=
array([88, 82, 62, 49, 34, 25, 89, 66, 68, 87, 74, 55, 30, 43,  2, 67, 16,
       70, 50, 96, 57, 13, 81, 76, 40,  3, 84, 92, 32, 26, 61, 45, 37, 98,
       93, 52,  4, 47, 83, 71, 63,  7, 21, 77, 64, 31, 69, 65, 20, 42, 85,
       38, 94, 41, 35, 51, 18, 58, 56, 95, 59,  6, 33, 60, 80, 19, 23, 99,
       10, 44,  9, 15, 53, 22, 39, 90, 11, 27, 14,  5, 48, 79, 29,  8, 75,
       86, 91, 12, 36, 46,  1, 97, 17, 28, 78, 72, 54, 24, 73],
      dtype=int32)>

In [85]:
# In the 2-D tensor the order of each individual element changes
# But the order within the inner tensor remains the same
ten_ns = tf.constant([[1,2],[3,4],[5,6]])
ten_ns

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [86]:
ten_s = tf.random.shuffle(ten_ns)
ten_s

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>