In [1]:
!which python

/home/asa/anaconda3/envs/TensorFlow-Development/bin/python


In [1]:
# Importing the packages
import tensorflow as tf

2024-08-08 16:53:03.572440: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [47]:
# Checking the tensorflow version
print(tf.__version__)

2.16.1


In [59]:
# Constants
c1 = tf.constant(7)
c1

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [60]:
# Check the dim of a tensor
c1.ndim

0

In [61]:
# Creating the vector
v1 = tf.constant([1,2,3])
print(v1)
print(v1.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1


In [62]:
# Creating the matrix
m1 = tf.constant([[1,2],
                  [3,4]])
print(m1)
print(m1.ndim)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
2


In [63]:
# Specifying the dtype for the tensor
print(c1.dtype)
c2=tf.constant(3, dtype=tf.int64)
print(c2.dtype)

<dtype: 'int32'>
<dtype: 'int64'>


In [64]:
m2 = tf.constant([[3.,2.],
                  [3.,42.]], dtype=tf.float64)
m2
# Does the tf stores the value of the tensors as a numpy array

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.,  2.],
       [ 3., 42.]])>

In [65]:
# Tensors with the higher dimension
t1 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[1,2]]])
t1

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [1, 2]]], dtype=int32)>

In [2]:
# Creating tensors with variables
changable_tensor = tf.Variable([2,4])
unchangable_tensor = 
v1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 4], dtype=int32)>